name: lint
on: pull_request

jobs:
  unit:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
        submodules: recursive

    - run: |
        # git submodule update --init --recursive
        ./hack/ci/lint-check.sh
